### ISSUE TITLE
Transition to OCIO2

### ISSUE THREAD

**Issue by devernay** [NatronGitHub/openfx-io#4]
I made a new branch, named `ocio2` to start the transition to OCIO2: https://github.com/NatronGitHub/openfx-io/tree/ocio2
I tried to keep OCIO1 compatibility, using `OCIO_VERSION_HEX`.

The code does not yet compile with OCIO 2.0.0 (I haven't fully figured out how to use the new API, since the Nuke plugins in the code were not updated).

There are a few changes remaining to be made, including #1

**Comment by devernay** [comment]
OK I made some progress there, all what's left is the OpenGL rendering stuff. OCIO has code which is significantly different from what can be found in OCIO1, and there's poor documentation and little to no example: https://github.com/AcademySoftwareFoundation/OpenColorIO/tree/master/src/libutils/oglapphelpers

The nuke plugins in OCIO were not updated either (well I guess foundry has their own updated version)

I'll put that on hold for the next month. Help is always welcome (@rodlie or others)

**Comment by devernay** [comment]
One option would be to disable OpenGL render on OCIO2

**Comment by devernay** [comment]
fixed by #17

**Comment by rodlie** [comment]
I'm not able to do a release build of 2.4.2 on Windows due to OCIO issues, do I need to change something in the build scripts since this change?

I used the build scripts from RB-2.4.

```
  CXX      MINGW64_NT-10.0-64-relwithdebinfo/glsl.o
In file included from ../IOSupport/GenericOCIOOpenGL.cpp:47:0:
../IOSupport/glsl.h:48:64: error: 'UniformData' in 'class OpenColorIO::v1::GpuShaderDesc' does not name a type
         Uniform(const std::string & name, const GpuShaderDesc::UniformData & data);
                                                                ^~~~~~~~~~~
../IOSupport/glsl.h:57:24: error: 'UniformData' in 'class OpenColorIO::v1::GpuShaderDesc' does not name a type
         GpuShaderDesc::UniformData m_data;
                        ^~~~~~~~~~~
../IOSupport/glsl.h:65:44: error: 'GpuShaderDescRcPtr' does not name a type
     static OpenGLBuilderRcPtr Create(const GpuShaderDescRcPtr & gpuShader);
                                            ^~~~~~~~~~~~~~~~~~
../IOSupport/glsl.h:91:25: error: 'GpuShaderDescRcPtr' does not name a type
     OpenGLBuilder(const GpuShaderDescRcPtr & gpuShader);
                         ^~~~~~~~~~~~~~~~~~
../IOSupport/glsl.h:108:11: error: 'GpuShaderDescRcPtr' does not name a type
     const GpuShaderDescRcPtr m_shaderDesc; // Description of the fragment shader to create
           ^~~~~~~~~~~~~~~~~~
make[1]: *** [../openfx/Support/Plugins/Makefile.master:83: MINGW64_NT-10.0-64-relwithdebinfo/GenericOCIOOpenGL.o] Error 1

```

**Comment by devernay** [comment]
You should compile against OCIO2, (and uninstall OCIO1 to make sure it's not using it)

**Comment by rodlie** [comment]
Ok, I will look at that tomorrow (it's getting late), I was not expecting breaking changes in 2.4.2 (I though v1 was still supported).

**Comment by devernay** [comment]
it's not breaking, its a library upgrade. it fixes rendering bugs. 
Latest OCIO version is 2.1.1

**Comment by devernay** [comment]
I just pushed a change that fixes compiling with OCIO1, but it should be avoided (because of the rendering bugs)

**Comment by rodlie** [comment]
I will add OCIO2 to the Windows RB-2.4 SDK tomorrow (I have the "legacy" SDK for RB-2.4 and another one for RB-2.5+), then do a build.

**Comment by rodlie** [comment]
I now have OCIO2, but still issues related to GLU:
```
make[1]: Entering directory '/home/Natron/workspace/tmp64/openfx-io/IO'
  CXX      MINGW64_NT-10.0-64-relwithdebinfo/ofxsThreadSuite.o
  CXX      MINGW64_NT-10.0-64-relwithdebinfo/tinythread.o
  CXX      MINGW64_NT-10.0-64-relwithdebinfo/ofxsFileOpen.o
  CXX      MINGW64_NT-10.0-64-relwithdebinfo/ofxsOGLTextRenderer.o
  CXX      MINGW64_NT-10.0-64-relwithdebinfo/ofxsOGLFontData.o
  CXX      MINGW64_NT-10.0-64-relwithdebinfo/ofxsRamp.o
  CXX      MINGW64_NT-10.0-64-relwithdebinfo/ofxsGenerator.o
  CXX      MINGW64_NT-10.0-64-relwithdebinfo/ofxsTransformInteract.o
  CXX      MINGW64_NT-10.0-64-relwithdebinfo/ofxsMultiPlane.o
  CXX      MINGW64_NT-10.0-64-relwithdebinfo/ofxsRectangleInteract.o
  CXX      MINGW64_NT-10.0-64-relwithdebinfo/ofxsLut.o
  CXX      MINGW64_NT-10.0-64-relwithdebinfo/GenericReader.o
  CXX      MINGW64_NT-10.0-64-relwithdebinfo/GenericWriter.o
  CXX      MINGW64_NT-10.0-64-relwithdebinfo/SequenceParsing.o
  CXX      MINGW64_NT-10.0-64-relwithdebinfo/SeExpr.o
  CXX      MINGW64_NT-10.0-64-relwithdebinfo/SeGrain.o
  CXX      MINGW64_NT-10.0-64-relwithdebinfo/SeNoise.o
  CXX      MINGW64_NT-10.0-64-relwithdebinfo/GenericOCIO.o
  CXX      MINGW64_NT-10.0-64-relwithdebinfo/GenericOCIOOpenGL.o
  CXX      MINGW64_NT-10.0-64-relwithdebinfo/glsl.o
  CXX      MINGW64_NT-10.0-64-relwithdebinfo/glad.o
  CXX      MINGW64_NT-10.0-64-relwithdebinfo/ofxsOGLUtilities.o
In file included from ../IOSupport/glsl.cpp:9:0:
C:/msys64-20180531/mingw64/x86_64-w64-mingw32/include/GL/glu.h:68:79: error: expected ')' before '*' token
 void APIENTRY gluQuadricCallback(GLUquadric *qobj,GLenum which,void (CALLBACK *fn)());
                                                                               ^
C:/msys64-20180531/mingw64/x86_64-w64-mingw32/include/GL/glu.h:68:79: error: expected ')' before '*' token
C:/msys64-20180531/mingw64/x86_64-w64-mingw32/include/GL/glu.h:68:79: error: expected initializer before '*' token
C:/msys64-20180531/mingw64/x86_64-w64-mingw32/include/GL/glu.h:78:79: error: expected ')' before '*' token
 void APIENTRY gluTessCallback(GLUtesselator *tess,GLenum which,void (CALLBACK *fn)());
                                                                               ^
C:/msys64-20180531/mingw64/x86_64-w64-mingw32/include/GL/glu.h:78:79: error: expected ')' before '*' token
C:/msys64-20180531/mingw64/x86_64-w64-mingw32/include/GL/glu.h:78:79: error: expected initializer before '*' token
C:/msys64-20180531/mingw64/x86_64-w64-mingw32/include/GL/glu.h:94:75: error: expected ')' before '*' token
 void APIENTRY gluNurbsCallback(GLUnurbs *nobj,GLenum which,void (CALLBACK *fn)());
                                                                           ^
C:/msys64-20180531/mingw64/x86_64-w64-mingw32/include/GL/glu.h:94:75: error: expected ')' before '*' token
C:/msys64-20180531/mingw64/x86_64-w64-mingw32/include/GL/glu.h:94:75: error: expected initializer before '*' token
C:/msys64-20180531/mingw64/x86_64-w64-mingw32/include/GL/glu.h:96:24: error: expected ')' before '*' token
 typedef void (CALLBACK *GLUquadricErrorProc)(GLenum);
                        ^
C:/msys64-20180531/mingw64/x86_64-w64-mingw32/include/GL/glu.h:97:24: error: expected ')' before '*' token
 typedef void (CALLBACK *GLUtessBeginProc)(GLenum);
                        ^
C:/msys64-20180531/mingw64/x86_64-w64-mingw32/include/GL/glu.h:98:24: error: expected ')' before '*' token
 typedef void (CALLBACK *GLUtessEdgeFlagProc) (GLboolean);
                        ^
C:/msys64-20180531/mingw64/x86_64-w64-mingw32/include/GL/glu.h:99:24: error: expected ')' before '*' token
 typedef void (CALLBACK *GLUtessVertexProc)(void *);
                        ^
C:/msys64-20180531/mingw64/x86_64-w64-mingw32/include/GL/glu.h:100:24: error: expected ')' before '*' token
 typedef void (CALLBACK *GLUtessEndProc)(void);
                        ^
C:/msys64-20180531/mingw64/x86_64-w64-mingw32/include/GL/glu.h:101:24: error: expected ')' before '*' token
 typedef void (CALLBACK *GLUtessErrorProc)(GLenum);
                        ^
C:/msys64-20180531/mingw64/x86_64-w64-mingw32/include/GL/glu.h:102:24: error: expected ')' before '*' token
 typedef void (CALLBACK *GLUtessCombineProc)(GLdouble[3],void*[4],GLfloat[4],void**);
                        ^
C:/msys64-20180531/mingw64/x86_64-w64-mingw32/include/GL/glu.h:103:24: error: expected ')' before '*' token
 typedef void (CALLBACK *GLUtessBeginDataProc)(GLenum,void *);
                        ^
C:/msys64-20180531/mingw64/x86_64-w64-mingw32/include/GL/glu.h:104:24: error: expected ')' before '*' token
 typedef void (CALLBACK *GLUtessEdgeFlagDataProc) (GLboolean,void *);
                        ^
C:/msys64-20180531/mingw64/x86_64-w64-mingw32/include/GL/glu.h:105:24: error: expected ')' before '*' token
 typedef void (CALLBACK *GLUtessVertexDataProc)(void *,void *);
                        ^
C:/msys64-20180531/mingw64/x86_64-w64-mingw32/include/GL/glu.h:106:24: error: expected ')' before '*' token
 typedef void (CALLBACK *GLUtessEndDataProc)(void *);
                        ^
C:/msys64-20180531/mingw64/x86_64-w64-mingw32/include/GL/glu.h:107:24: error: expected ')' before '*' token
 typedef void (CALLBACK *GLUtessErrorDataProc)(GLenum,void *);
                        ^
C:/msys64-20180531/mingw64/x86_64-w64-mingw32/include/GL/glu.h:108:24: error: expected ')' before '*' token
 typedef void (CALLBACK *GLUtessCombineDataProc)(GLdouble[3],void*[4],GLfloat[4],void**,void*);
                        ^
C:/msys64-20180531/mingw64/x86_64-w64-mingw32/include/GL/glu.h:109:24: error: expected ')' before '*' token
 typedef void (CALLBACK *GLUnurbsErrorProc)(GLenum);
                        ^
make[1]: *** [../openfx/Support/Plugins/Makefile.master:83: MINGW64_NT-10.0-64-relwithdebinfo/glsl.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/Natron/workspace/tmp64/openfx-io/IO'
make: *** [Makefile:23: IO] Error 2

```

**Comment by devernay** [comment]
This should be fixed by https://github.com/NatronGitHub/openfx-io/commit/b1840bef01159dad36d9619cb3de6cd3e879a218

Concerning the SDK, you should be able to use the same SDK for all versions. That's what I do on macOS and Linux, where w have python2+3 and Qt4+5 in the same sdk.

**Comment by rodlie** [comment]
Thanks, just started a new build.

The RB-2.5 SDK is not done yet, so for now I have to run two SDK's.

**Comment by rodlie** [comment]
```
make[1]: Entering directory '/home/Natron/workspace/tmp64/openfx-io/IO'
  CXX      MINGW64_NT-10.0-64-relwithdebinfo/ofxsThreadSuite.o
  CXX      MINGW64_NT-10.0-64-relwithdebinfo/tinythread.o
  CXX      MINGW64_NT-10.0-64-relwithdebinfo/ofxsFileOpen.o
  CXX      MINGW64_NT-10.0-64-relwithdebinfo/ofxsOGLTextRenderer.o
  CXX      MINGW64_NT-10.0-64-relwithdebinfo/ofxsOGLFontData.o
  CXX      MINGW64_NT-10.0-64-relwithdebinfo/ofxsRamp.o
  CXX      MINGW64_NT-10.0-64-relwithdebinfo/ofxsGenerator.o
  CXX      MINGW64_NT-10.0-64-relwithdebinfo/ofxsTransformInteract.o
  CXX      MINGW64_NT-10.0-64-relwithdebinfo/ofxsMultiPlane.o
  CXX      MINGW64_NT-10.0-64-relwithdebinfo/ofxsRectangleInteract.o
  CXX      MINGW64_NT-10.0-64-relwithdebinfo/ofxsLut.o
  CXX      MINGW64_NT-10.0-64-relwithdebinfo/GenericReader.o
  CXX      MINGW64_NT-10.0-64-relwithdebinfo/GenericWriter.o
  CXX      MINGW64_NT-10.0-64-relwithdebinfo/SequenceParsing.o
  CXX      MINGW64_NT-10.0-64-relwithdebinfo/SeExpr.o
  CXX      MINGW64_NT-10.0-64-relwithdebinfo/SeGrain.o
  CXX      MINGW64_NT-10.0-64-relwithdebinfo/SeNoise.o
  CXX      MINGW64_NT-10.0-64-relwithdebinfo/GenericOCIO.o
  CXX      MINGW64_NT-10.0-64-relwithdebinfo/GenericOCIOOpenGL.o
  CXX      MINGW64_NT-10.0-64-relwithdebinfo/glsl.o
  CXX      MINGW64_NT-10.0-64-relwithdebinfo/glad.o
In file included from ../IOSupport/glsl.cpp:27:0:
C:\msys64-20180531\mingw64\include/GL/glew.h:85:2: error: #error gl.h included before glew.h
 #error gl.h included before glew.h
  ^~~~~
../IOSupport/glsl.cpp:4:0: error: unterminated #if
 #if 1

```

**Comment by devernay** [comment]
fixed again - not using glu.h from mingw32, since it seems to be broken

**Comment by rodlie** [comment]
Thanks, it now builds.

There are however issues, the IO.ofx binary will not load (the dependencies are ok). Will need to figure out why.

OCIO2 seems to work as I can use the readers from openfx-arena that are also linked against OCIO2.

**Comment by rodlie** [comment]
So, I still got no solution for IO.ofx not loading on Windows. If I build against OCIO1 everything works fine, and IO.ofx is loaded.

I can only assume that IOSupport/glsl breaks something on Windows(?).

I have time tomorrow to look more into this.

btw, I uploaded 2.4.2 release binaries for Windows with OCIO1 (better than nothing).
